force-app/main/default/objects/Main_Master__c/Main_Master__c.object-meta.xml
<CustomObject>
    <label>Main Master</label>
    <nameField>
        <label>Main Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Main_Master__c/fields/First_part_of_secret__c.field-meta.xml
<CustomField>
    <fullName>First_part_of_secret__c</fullName>
    <label>First part of secret</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Link__c/Master_Link__c.object-meta.xml
<CustomObject>
    <label>Master Link</label>
    <nameField>
        <label>Master Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Link__c/fields/Main_Master__c.field-meta.xml
<CustomField>
    <fullName>Main_Master__c</fullName>
    <label>Main Master</label>
    <referenceTo>Main_Master__c</referenceTo>
    <relationshipLabel>Master Links</relationshipLabel>
    <relationshipName>Master_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Link__c/fields/Second_Master__c.field-meta.xml
<CustomField>
    <fullName>Second_Master__c</fullName>
    <label>Second Master</label>
    <referenceTo>Second_Master__c</referenceTo>
    <relationshipLabel>Master Links</relationshipLabel>
    <relationshipName>Master_Links</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Second_Master__c/Second_Master__c.object-meta.xml
<CustomObject>
    <label>Second Master</label>
    <nameField>
        <label>Second Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Second Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Second_Master__c/fields/Second_part_of_secret__c.field-meta.xml
<CustomField>
    <fullName>Second_part_of_secret__c</fullName>
    <label>Second part of secret</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TwoMastersSecret.cls
/**
 * Created by kam on 27.02.21.
 */

public with sharing class TwoMastersSecret {


    public static void joinSecret(Main_Master__c master1, Second_Master__c master2) {
        String str1 = master1.First_part_of_secret__c;
        String str2 = master2.Second_part_of_secret__c;
    }
    public static void joinSecret2(Master_Link__c masterLink) {
        String str1 = masterLink.Main_Master__r.First_part_of_secret__c;
        String str2 = masterLink.Second_Master__r.Second_part_of_secret__c;
        //invisible man
    }


}